### ISSUE TITLE
Guidance needed for php 5.6

### ISSUE THREAD

**Issue by N6REJ** [wagy/WinBinder#13]
This is going to sound really strange but for the forseeable future we're stuck using a maximum of php 5.6.40
we are currently using php 5.4.32 but thats stopping us from using tls 1.2 
Can we use your instructions and source and build winbinder for vc11? i.e. 5.6.40?
I appreciate your time on this.
We want to move to php 7.2 but this can't happen for at least a year.

**Comment by wagy** [comment]
Hi, this works with

g:\dev\php\php56ts>php --version
PHP 5.6.37 (cli) (built: Jul 19 2018 18:40:33)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
[php_winbinder.zip](https://github.com/wagy/WinBinder/files/15141297/php_winbinder.zip)

**Comment by N6REJ** [comment]
oh my gosh, your a blessing!!!
What would you use to replace php_win32ps.dll?  We have one for 5.6 but when we go to 7 we're going to be hosed as its a critical part of http://github.com/Bearsampp/Baersampp

**Comment by wagy** [comment]
No we dont use this
