### ISSUE TITLE
dll release

### ISSUE THREAD

**Issue by ghostjat** [wagy/WinBinder#4]
would you please release dll .

**Comment by wagy** [comment]
https://github.com/wagy/WinBinder/releases/download/untagged-51e451127de0b0ac8ec6/php_winbinder.dll
For php 7

**Comment by SalimF** [comment]
> https://github.com/wagy/WinBinder/releases/download/untagged-51e451127de0b0ac8ec6/php_winbinder.dll For php 7

They file were deleted can I have another link, or how to compile it?
