### ISSUE TITLE
PHP7 vs. C-Strings

### ISSUE THREAD

**Issue by mastacheata** [wagy/WinBinder#6]
Apparently the extension still has problems with returning C-strings to PHP instead of properly passing zend_strings or at least strings that aren't 0-byte terminated.

A good example is the ttfreader.phpw, which will select a file using the wb_sys_dlg_open and then tries to fopen the returned filename. That fails horribly because of the surplus \0 at the end of the string returned.
Once you remove that, it works just fine.

Sadly there is very little documentation on how to handle that properly.
The PECL OAUTH extension simply stripped the last byte from those strings that were broken in their extension (https://github.com/php/pecl-web_services-oauth/pull/1/commits/7a4f5ff29bf483649cb759c4bf8eaa69ab00bfa9), but that's probably not the "right way" to do it.

If you got a general idea how to fix that behavior properly, I'll be glad to do the changes and fix it.
My C experience is limited, I understand C programs, but barely ever write C code myself.

**Comment by wagy** [comment]
Yes there is a problem when the return value is converted from UTF-16 (MS) to UTF-8. 
WideCharToMultiByte  returns the length with zerobyte.

if (!BITTEST(style, WBC_MULTISELECT))
{
	file = WideChar2Utf8(szFile, &file_len);
	//RETURN_STRINGL(file, file_len);
	RETURN_STRING(file);
}
This fixed the problem about return value on wb_sys_dlg_open.


I see the same problem on list and treeview !

[php_winbinder.zip](https://github.com/wagy/WinBinder/files/2515351/php_winbinder.zip)
